[package]
name = "nael_core"
authors = ["Blooym"]
description = "Internals for managing different installations of Dalamud."
version = "0.3.0"
license = "MIT OR Apache-2.0"
rust-version = "1.75.0"
edition = "2021"
homepage = "https://github.com/Blooym/Nael"
repository = "https://github.com/Blooym/Nael"
publish = true
keywords = ["dalamud", "version-manager", "ffxiv"]

[dependencies]
zip = "0.6.6"
anyhow = { version = "1.0.79", features = ["backtrace"] }
directories = "5.0.1"
indicatif = "0.17.8"
reqwest = { version = "0.11.24", features = [
    "rustls-tls",
], default_features = false }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
symlink = "0.1.0"
tempfile = "3.10.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
clone_on_ref_ptr = "warn"
