[package]
name = "nael_core"
authors = ["Blooym"]
description = "Internals for managing different installations of Dalamud."
version = "0.4.2"
license = "MIT OR Apache-2.0"
rust-version = "1.75.0"
edition = "2021"
repository = "https://github.com/Blooym/nael"
publish = true
keywords = ["dalamud", "version-manager", "ffxiv"]

[features]
default = ["rustls-tls"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
zip = "2.2.0"
anyhow = { version = "1.0.89", features = ["backtrace"] }
directories = "5.0.1"
indicatif = "0.17.8"
reqwest = { version = "0.12.7", features = [
    "charset",
    "macos-system-configuration",
    "http2",
], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
symlink = "0.1.0"
tempfile = "3.12.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
clone_on_ref_ptr = "warn"
