[package]
name = "nael_core"
authors = ["Blooym"]
description = "Internals for managing different installations of Dalamud."
version = "0.4.1"
license = "MIT OR Apache-2.0"
rust-version = "1.75.0"
edition = "2021"
homepage = "https://github.com/Blooym/Nael"
repository = "https://github.com/Blooym/Nael"
publish = true
keywords = ["dalamud", "version-manager", "ffxiv"]

[features]
default = ["rustls-tls"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
zip = "0.6.6"
anyhow = { version = "1.0.81", features = ["backtrace"] }
directories = "5.0.1"
indicatif = "0.17.8"
reqwest = { version = "0.12.0", features = [
    "charset",
    "macos-system-configuration",
    "http2",
], default_features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
symlink = "0.1.0"
tempfile = "3.10.1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
clone_on_ref_ptr = "warn"
