[package]
name = "nael_core"
authors = ["Blooym"]
description = "Install and manage different installations of Dalamud quickly and easily."
version = "0.1.1"
license = "MIT OR Apache-2.0"
rust-version = "1.75.0"
edition = "2021"
publish = false

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
# pedantic = "warn"
clone_on_ref_ptr = "warn"

[dependencies]
zip = "0.6.6"
anyhow = { version = "1.0.79", features = ["backtrace"] }
directories = "5.0.1"
indicatif = "0.17.7"
reqwest = { version = "0.11.24", features = [
    "rustls-tls",
], default_features = false }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
symlink = "0.1.0"
tempfile = "3.10.0"
